# ----------------------------------------------------------------
# Home Assistant core configuration file
#
# REPO: https://github.com/JesseWebDotCom/home-assistant-configuration
#----------------------------------------------------------------

homeassistant:
# -----------------------------------------------------------------
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: !secret homeassistant_time_zone
  customize: !include config/customize.yaml
  customize_glob: !include config/components/customize_glob.yaml
  packages: !include_dir_named config/packages/

#----------------------------------------------------------------
# COMPONENTS
#----------------------------------------------------------------

automation: !include config/components/automations.yaml
binary_sensor: !include config/components/binary_sensor.yaml
bmw_connected_drive: !include config/components/bmw_connected_drive.yaml
camera: !include config/components/camera.yaml
fan:
config:
device_tracker: !include config/components/device_tracker.yaml
discovery:
ecobee: !include config/components/ecobee.yaml
frontend: !include config/components/frontend.yaml
hassio:
history: !include config/components/history.yaml
http: !include config/components/http.yaml
homekit: !include config/components/homekit.yaml
juicenet: !include config/components/juicenet.yaml
logbook: !include config/components/logbook.yaml
logger: !include config/components/logger.yaml
lovelace: !include config/components/lovelace.yaml
map:
media_player: !include config/components/media_player.yaml
notify: !include config/components/notifiers.yaml
ring: !include config/components/ring.yaml
sabnzbd: !include config/components/sabnzbd.yaml
sense: !include config/components/sense.yaml
sensor: !include config/components/sensor.yaml
sun:
system_health:
telegram_bot: !include config/components/telegram_bot.yaml
tts: !include config/components/tts.yaml
updater:
volvooncall: !include config/components/volvooncall.yaml
zwave: 
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key
zha: 
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db