title: Home

resources:
  - url: /local/custom-lovelace/useful-markdown-card/useful-markdown-card.js?v=0
    type: js
  - url: /local/custom-lovelace/mini-media-player/mini-media-player.js?v=0.9.8
    type: module
  - url: /local/custom-lovelace/monster-card/monster-card.js?v=1
    type: js
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v0
    type: js
  - url: /local/custom-lovelace/button-card/button-card.js
    type: module       

name: Home
views:
  - title: Home
    id: home
    icon: mdi:home
    cards: !include config/views/home.yaml

  # - title: Security
  #   id: security
  #   icon: mdi:shield
  #   cards: !include config/view_cards/security.yaml
  
  # - title: Exterior
  #   id: exterior
  #   icon: mdi:pine-tree
  #   cards: !include config/view_cards/exterior.yaml
  
  - title: Upstairs
    id: upstairs
    icon: mdi:arrow-up-bold
    cards: !include config/views/upstairs.yaml

  - title: Downstairs
    id: downstairs
    icon: mdi:arrow-down-bold
    cards: !include config/views/downstairs.yaml

  - title: People
    id: people
    icon: mdi:account-multiple
    cards: !include config/views/people.yaml    

  - title: Cars
    id: cars
    icon: mdi:car
    cards: !include config/views/cars.yaml
    
  - title: Options
    id: options
    icon: mdi:settings
    cards: !include config/views/options.yaml
