themes:
  critical:
      primary-text-color: "white"
      paper-card-background-color: "darkred"

  warning:
      primary-text-color: "white"
      paper-card-background-color: "#666600"
      
  Dark - Cyan:
    paper-card-header-color: "#FFFFFF"

    ### Main Interface Colors ###
    primary-color: "#00E4D7"
    light-primary-color: "#71FFF7"
    primary-background-color: "#1F1F28"
    secondary-background-color: var(--primary-background-color)
    divider-color: "#2C2C39"
    ### Text ###
    primary-text-color: "#F7F8FA"
    secondary-text-color: "#00E2D8"
    text-primary-color: "#FFFFFF"
    disabled-text-color: "#5B7283"
    ### Sidebar Menu ###
    sidebar-icon-color: "#BCC5D1"
    sidebar-text-color: "#F7F8FA"
    sidebar-selected-background-color: var(--primary-background-color)
    sidebar-selected-icon-color: "#00E2D8"
    sidebar-selected-text-color: var(--sidebar-selected-icon-color)
    ### States and Badges ###
    state-icon-color: "#00C5E3"
    state-icon-active-color: "#FBCD41"
    state-icon-unavailable-color: var(--disabled-text-color)
    ### Sliders ###
    paper-slider-knob-color: "#00E2D8"
    paper-slider-knob-start-color: var(--paper-slider-knob-color)
    paper-slider-pin-color: var(--paper-slider-knob-color)
    paper-slider-active-color: var(--paper-slider-knob-color)
    paper-slider-secondary-color: "#00C5E3"
    ### Labels ###
    label-badge-background-color: "#2F2F3D"
    label-badge-text-color: "#F7F8FA"
    label-badge-red: "#444459"
    ### Cards ###
    paper-card-background-color: "#23232E"
    paper-listbox-background-color: var(--primary-background-color)
    ### Toggles ###
    paper-toggle-button-checked-button-color: "#00E2D8"
    paper-toggle-button-checked-bar-color: "#00EDE0"
    paper-toggle-button-unchecked-button-color: "#A8B3C3"
    paper-toggle-button-unchecked-bar-color: "#CED5DD"
    ### Table row ###
    table-row-background-color: var(--primary-background-color)
    table-row-alternative-background-color: var(--secondary-background-color)

  Light - Cyan:
    ### Main Interface Colors ###
    primary-color: "#00E4D7"
    light-primary-color: "#71FFF7"
    primary-background-color: "#F7F8FA"
    secondary-background-color: var(--primary-background-color)
    divider-color: "#E4E8EE"
    ### Text ###
    primary-text-color: "#6D7A8C"
    secondary-text-color: "#007f79" #"#00E2D8"
    text-primary-color: "#FFFFFF"
    disabled-text-color: "#BECAD2"
    ### Sidebar Menu ###
    sidebar-icon-color: "#BCC5D1"
    sidebar-text-color: "#6D7A8C"
    sidebar-selected-background-color: var(--primary-background-color)
    sidebar-selected-icon-color: "#00E2D8"
    sidebar-selected-text-color: var(--sidebar-selected-icon-color)
    ### States and Badges ###
    state-icon-color: "#00C5E3"
    state-icon-active-color: "#FBCD41"
    state-icon-unavailable-color: var(--disabled-text-color)
    ### Sliders ###
    paper-slider-knob-color: "#00E2D8"
    paper-slider-knob-start-color: var(--paper-slider-knob-color)
    paper-slider-pin-color: var(--paper-slider-knob-color)
    paper-slider-active-color: var(--paper-slider-knob-color)
    paper-slider-secondary-color: "#00C5E3"
    ### Labels ###
    label-badge-background-color: "#F7F8FA"
    label-badge-text-color: "#6D7A8C"
    label-badge-red: "#BCC5D1"
    ### Cards ###
    paper-card-background-color: "#FBFBFD"
    paper-listbox-background-color: var(--primary-background-color)
    ### Toggles ###
    paper-toggle-button-checked-button-color: "#00E2D8"
    paper-toggle-button-checked-bar-color: "#00EDE0"
    paper-toggle-button-unchecked-button-color: "#A8B3C3"
    paper-toggle-button-unchecked-bar-color: "#CED5DD"
    ### Table row ###
    table-row-background-color: var(--primary-background-color)
    table-row-alternative-background-color: var(--secondary-background-color)

  Dark - Light Red:
    ### Main Interface Colors ###
    primary-color: "#FF6262"
    light-primary-color: "#FF8888"
    primary-background-color: "#20252F"
    secondary-background-color: var(--primary-background-color)
    divider-color: "#2F2F3D"
    ### Text ###
    primary-text-color: "#FFFFFF"
    secondary-text-color: "#FF8888"
    text-primary-color: "#FFFFFF"
    disabled-text-color: "#5B5B77"
    ### Sidebar Menu ###
    sidebar-icon-color: "#7D8BA6"
    sidebar-text-color: "#F1F1F1"
    sidebar-selected-background-color: var(--primary-background-color)
    sidebar-selected-icon-color: "#FF8888"
    sidebar-selected-text-color: var(--sidebar-selected-icon-color)
    ### States and Badges ###
    state-icon-color: "#FF6262"
    state-icon-active-color: "#FBCD41"
    state-icon-unavailable-color: var(--disabled-text-color)
    ### Sliders ###
    paper-slider-knob-color: "#FF6262"
    paper-slider-knob-start-color: var(--paper-slider-knob-color)
    paper-slider-pin-color: var(--paper-slider-knob-color)
    paper-slider-active-color: var(--paper-slider-knob-color)
    paper-slider-secondary-color: var(--light-primary-color)
    ### Labels ###
    label-badge-background-color: "#252B36"
    label-badge-text-color: "#F1F1F1"
    label-badge-red: "#6C7B9B"
    ### Cards ###
    paper-card-background-color: "#252B36"
    paper-listbox-background-color: var(--primary-background-color)
    ### Toggles ###
    paper-toggle-button-checked-button-color: "#FF6262"
    paper-toggle-button-checked-bar-color: "#FFA3A3"
    paper-toggle-button-unchecked-button-color: "#6C7B9B"
    paper-toggle-button-unchecked-bar-color: "#434E62"
    ### Table row ###
    table-row-background-color: var(--primary-background-color)
    table-row-alternative-background-color: var(--secondary-background-color)

  Light - Light Red:
    ### Main Interface Colors ###
    primary-color: "#FF6262"
    light-primary-color: "#FF8888"
    primary-background-color: "#F6F7F9"
    secondary-background-color: var(--primary-background-color)
    divider-color: "#D6DFEB"
    ### Text ###
    primary-text-color: "#395274"
    secondary-text-color: "#FF6262"
    text-primary-color: "#FFFFFF"
    disabled-text-color: "#88A1C4"
    ### Sidebar Menu ###
    sidebar-icon-color: "#395274"
    sidebar-text-color: var(--sidebar-icon-color)
    sidebar-selected-background-color: var(--primary-background-color)
    sidebar-selected-icon-color: "#FF6262"
    sidebar-selected-text-color: var(--sidebar-selected-icon-color)
    ### States and Badges ###
    state-icon-color: "#FF6262"
    state-icon-active-color: "#FBCD41"
    state-icon-unavailable-color: var(--disabled-text-color)
    ### Sliders ###
    paper-slider-knob-color: "#FF6262"
    paper-slider-knob-start-color: var(--paper-slider-knob-color)
    paper-slider-pin-color: var(--paper-slider-knob-color)
    paper-slider-active-color: var(--paper-slider-knob-color)
    paper-slider-secondary-color: var(--light-primary-color)
    ### Labels ###
    label-badge-background-color: "#FFFFFF"
    label-badge-text-color: "#395274"
    label-badge-red: "#395274"
    ### Cards ###
    paper-card-background-color: "#FFFFFF"
    paper-listbox-background-color: var(--primary-background-color)
    ### Toggles ###
    paper-toggle-button-checked-button-color: "#FF6262"
    paper-toggle-button-checked-bar-color: "#FFA3A3"
    paper-toggle-button-unchecked-button-color: "#395274"
    paper-toggle-button-unchecked-bar-color: "#9CB2CE"
    ### Table row ###
    table-row-background-color: var(--primary-background-color)
    table-row-alternative-background-color: var(--secondary-background-color)
