# https://www.home-assistant.io/components/homekit/

auto_start: false

filter:
  include_entities:
    - alarm.home_alarm
    - climate.downstairs_ecobee
    - climate.theater_ecobee
    - climate.upstairs_ecobee
    - cover.garage
    - fan.living_room
    - fan.master_bedroom_front
    - fan.master_bedroom_rear
    - light.biancas_room_dome
    - light.biancas_room_lava_lamp
    - light.dining_room_pendant
    - light.downstairs_bathroom_sconce
    - light.front_door_sconce
    - light.isabellas_room_dome
    - light.living_room_pendant
    - light.master_bedroom_carina_lamp
    - light.master_bedroom_front_pendant
    - light.master_bedroom_jesse_lamp
    - light.master_bedroom_rear_pendant
    - light.master_bedroom_wall_sconce
    - light.mudroom_entrance_dome
    - light.mudroom_hallway_dome
    - light.office_dome
    - light.playroom_dome
    - light.pool_spotlight
    - light.ryans_room_dome
    - light.sunroom_left_sconce
    - light.theater_wall_sconce
    - light.upstairs_attic
    - light.upstairs_bathroom_sconce
    - light.upstairs_hallway_recessed
    - light.upstairs_laundry
    - light.upstairs_stairs
    - lock.i3_94_rex_lock
    - lock.volvo_xc90_door_lock
    - media_player.bianca_s_room_ump
    - media_player.dining_room_cast
    - media_player.downstairs_bathroom_cast
    - media_player.home_cast
    - media_player.isabella_s_room_ump
    - media_player.kitchen_cast
    - media_player.kitchen_sink_cast
    - media_player.kitchen_table_cast
    - media_player.kitchen_ump
    - media_player.living_room_cast
    - media_player.living_room_ump
    - media_player.master_bathroom_cast
    - media_player.master_bedroom_cast
    - media_player.master_bedroom_ump
    - media_player.office_ump
    - media_player.playroom_ump
    - media_player.ryan_s_room_ump
    - media_player.theater_cast
    - media_player.theater_ump
    - media_player.upstairs_bathroom_cast
    - media_player.upstairs_hallway_cast
    - switch.boiler_room_pendant
    - switch.downstairs_bathroom_fan
    - switch.driveway_sconce
    - switch.garage_dome
    - switch.isabellas_room_accessory_left
    - switch.kitchen_pendant
    - switch.kitchen_recessed
    - switch.master_bedroom_ac
    - switch.porch_sconce
    - switch.sunroom_center_sconce
    - switch.sunroom_right_sconce
    - switch.theater_candy
    - switch.theater_posters
    - switch.upstairs_bathroom_fan2
    - switch.volvo_xc90_engine
    - switch.volvo_xc90_heater
entity_config:
  alarm_control_panel.home_alarm:
    name: Home Alarm
    code: !secret alarm_code
  climate.downstairs_ecobee:
    name: Downstairs
  climate.theater_ecobee:
    name: Theater
  climate.upstairs_ecobee:
    name: Upstairs
  cover.garage:
    name: Garage Door
  fan.living_room:
    name: Living Room Fan
  fan.master_bedroom_front:
    name: Master Bedroom Front Fan
  fan.master_bedroom_rear:
    name: Master Bedroom Rear Fan
  light.biancas_room_dome:
    name: Biancas Room Light
  light.biancas_room_lava_lamp:
    name: Biancas Room Lava Lamp
  light.dining_room_pendant:
    name: Dining Room Light
  light.downstairs_bathroom_sconce:
    name: Downstairs Bathroom Light
  light.front_door_sconce:
    name: Front Door Light
  light.isabellas_room_dome:
    name: Isabellas Room Light
  light.living_room_pendant:
    name: Living Room Light
  light.master_bedroom_carina_lamp:
    name: Master Bedroom Carina Lamp
  light.master_bedroom_front_pendant:
    name: Master Bedroom Front Light
  light.master_bedroom_jesse_lamp:
    name: Master Bedroom Jesse Lamp
  light.master_bedroom_rear_pendant:
    name: Master Bedroom Rear Light
  light.master_bedroom_wall_sconce:
    name: Master Bedroom Wall Light
  light.mudroom_entrance_dome:
    name: Mudroom Entrance Light
  light.mudroom_hallway_dome:
    name: Mudroom Hallway Light
  light.office_dome:
    name: Office Light
  light.playroom_dome:
    name: Playroom Light
  light.pool_spotlight:
    name: Pool Spotlight
  light.ryans_room_dome:
    name: Ryans Room Light
  light.sunroom_left_sconce:
    name: Sunroom Left Light
  light.theater_wall_sconce:
    name: Theater Wall Light
  light.upstairs_attic:
    name: Attic Light
  light.upstairs_bathroom_sconce:
    name: Upstairs Bathroom Light
  light.upstairs_hallway_recessed:
    name: Hallway Light        
  light.upstairs_laundry:
    name: Laundry Light        
  light.upstairs_stairs:
    name: Stairs Light  
  lock.i3_94_rex_lock:
    name: BMW Lock       
  lock.volvo_xc90_door_lock:
    name: Volvo Lock       
  media_player.bianca_s_room_ump:
    name: Biancas Room Apple TV
    feature_list:
      - feature: play_pause 
  media_player.dining_room_cast:
    name: Dining Room Cast
    feature_list:
      - feature: play_pause
  media_player.downstairs_bathroom_cast:
    name: Downstairs Bathroom Cast
    feature_list:
      - feature: play_pause
  media_player.home_cast:
    name: Home Cast
    feature_list:
      - feature: play_pause   
  media_player.isabella_s_room_ump:
    name: Isabellas Room Apple TV
    feature_list:
      - feature: play_pause
  media_player.kitchen_cast:
    name: Kitchen Cast
    feature_list:
      - feature: play_pause     
  media_player.kitchen_sink_cast:
    name: Kitchen Sink Cast
    feature_list:
      - feature: play_pause     
  media_player.kitchen_table_cast:
    name: Kitchen Table Cast
    feature_list:
      - feature: play_pause  
  media_player.kitchen_ump:
    name: Kitchen Apple TV
    feature_list:
      - feature: play_pause   
  media_player.living_room_cast:
    name: Living Room Cast
    feature_list:
      - feature: play_pause                                
  media_player.living_room_ump:
    name: Living Room Apple TV
    feature_list:
      - feature: play_pause                                
  media_player.master_bathroom_cast:
    name: Master Bathroom Cast
    feature_list:
      - feature: play_pause                                
  media_player.master_bedroom_cast:
    name: Master Bedroom Cast
    feature_list:
      - feature: play_pause   
  media_player.master_bedroom_ump:
    name: Master Bedroom Apple TV
    feature_list:
      - feature: play_pause                                      
  media_player.office_ump:
    name: Office Apple TV
    feature_list:
      - feature: play_pause                                      
  media_player.playroom_ump:
    name: Playroom Apple TV
    feature_list:
      - feature: play_pause  
  media_player.ryan_s_room_ump:
    name: Ryans Room Apple TV
    feature_list:
      - feature: play_pause  
  media_player.theater_cast:
    name: Theater Cast
    feature_list:
      - feature: play_pause                                                  
  media_player.theater_ump:
    name: Theater Apple TV
    feature_list:
      - feature: play_pause                                                  
  media_player.upstairs_bathroom_cast:
      name: Upstairs Bathroom Cast
      feature_list:
        - feature: play_pause   
  media_player.upstairs_hallway_cast:
      name: Hallway Cast
      feature_list:
        - feature: play_pause   
  switch.boiler_room_pendant:
      name: Boiler Room Light
      type: switch
  switch.downstairs_bathroom_fan:
      name: Downstairs Bathroom Fan
      type: switch      
  switch.driveway_sconce:
      name: Driveway Light
      type: switch      
  switch.garage_dome:
      name: Garage Light
      type: switch   
  switch.isabellas_room_accessory_left:
      name: Isabellas Room Desk Light
      type: outlet            
  switch.kitchen_pendant:
      name: Kitchen Table Light
      type: switch   
  switch.kitchen_recessed:
      name: Kitchen Ceiling Light
      type: switch   
  switch.master_bedroom_ac:
      name: Master Bedroom AC
      type: outlet            
  switch.porch_sconce:
      name: Porch Light
      type: switch   
  switch.sunroom_center_sconce:
        name: Sunroom Center Light
        type: switch      
  switch.sunroom_right_sconce:
        name: Sunroom Right Light
        type: switch               
  switch.theater_candy:
      name: Theater Candy
      type: outlet   
  switch.theater_posters:
        name: Theater Posters
        type: switch   
  switch.upstairs_bathroom_fan2:
        name: Upstairs Bathroom Fan
        type: switch  
  switch.volvo_xc90_engine:
        name: Volvo Engine
        type: switch                               
  switch.volvo_xc90_heater:
        name: Volvo Heater
        type: switch                               