server_port: !secret http_server_port
ssl_profile: intermediate
cors_allowed_origins:
  - https://google.com
  - https://www.home-assistant.io
use_x_forwarded_for: true
trusted_proxies:
  - 127.0.0.1
  - ::1
trusted_networks:
  - 127.0.0.1
  - ::1
  - 192.168.0.0/24
  - fd00::/8
ip_ban_enabled: true
login_attempts_threshold: 5
