- platform: plex
  entity_namespace: 'plex'
  include_non_clients: true
  scan_interval: 5
  use_custom_entity_ids: true
  use_episode_art: true
  remove_unavailable_clients: true
  client_remove_interval: 600

- platform: samsungtv
  name: Living Room | TV
  host: !secret samsungtv_living_room_host
  mac: !secret samsungtv_living_room_mac

- platform: universal
  name: Living Room | UMP
  icon: mdi:video
  children:
    - media_player.living_room_apple_tv
    - media_player.living_room_plex

- platform: universal
  name: Kitchen | UMP
  icon: mdi:video
  children:
    - media_player.kitchen_apple_tv
    - media_player.kitchen_plex

- platform: universal
  name: Isabella's Room | UMP
  icon: mdi:video
  children:
    - media_player.isabellas_room_apple_tv
    - media_player.isabellas_room_plex

- platform: universal
  name: Bianca's Room | UMP
  icon: mdi:video
  children:
    - media_player.biancas_room_apple_tv
    - media_player.biancas_room_plex

- platform: universal
  name: Master Bedroom | UMP
  icon: mdi:video
  children:
    - media_player.master_bedroom_apple_tv
    - media_player.master_bedroom_plex

- platform: universal
  name: Ryan's Room | UMP
  icon: mdi:video
  children:
    - media_player.ryans_room_apple_tv
    - media_player.ryans_room_plex

- platform: universal
  name: Office | UMP
  icon: mdi:video
  children:
    - media_player.office_apple_tv
    - media_player.office_plex

- platform: universal
  name: Theater | UMP
  icon: mdi:video
  children:
    - media_player.theater_plex
    - media_player.theater_plex

- platform: universal
  name: Playroom | UMP
  icon: mdi:video
  children:
    - media_player.playroom_plex
    - media_player.playroom_plex    