# https://www.home-assistant.io/components/sensor.ring/
- platform: ring

# https://www.home-assistant.io/components/sensor.synologydsm/
- platform: synologydsm
  host: !secret synologydsm_host_d8
  username: !secret synologydsm_username
  password: !secret synologydsm_password
  monitored_conditions:
    - volume_percentage_used
    - volume_status
    - volume_size_total

- platform: synologydsm
  host: !secret synologydsm_host_d5
  username: !secret synologydsm_username
  password: !secret synologydsm_password
  monitored_conditions:
    - volume_percentage_used
    - volume_status
    - volume_size_total

# https://www.home-assistant.io/components/sensor.solaredge/
- platform: solaredge
  api_key: ! secret solaredge_api_key
  site_id: ! secret solaredge_api_key
  name: SolarEdge
  monitored_conditions:
    - lifetime_energy
    - energy_this_year
    - energy_this_month
    - energy_today
    - current_power

- platform: plex_recently_added
  token: !secret plex_token
  server_name: !secret plex_server_name
  ssl: true
  ssl_cert: false
  download_images: false
  max: 5
  section_types:
  - movie
  - show

- platform: radarr_upcoming_media
  api_key: !secret radarr_api_key
  host: !secret radarr_host
  port: !secret radarr_port
  days: 120
  ssl: false
  theaters: false
  max: 10

- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api_key
  host: !secret sonarr_host
  port: !secret sonarr_port
  days: 2
  ssl: false
  max: 10  