binary_sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      boiler_room_moisture:
        value_template: "{{ is_state('sensor.boiler_room_leak_sensor_flood', '2') }}"

script:
#----------------------------------------------------------------

  boiler_room_poweroff_all:
    alias: "Boiler Room | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.boiler_room_poweroff_lights

  boiler_room_poweroff_lights:
    alias: "Boiler Room | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - switch.boiler_room_pendant

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      boiler_room_on:
        friendly_name: Boiler Room | On
        value_template: >
          {% set total = 0 %}

          {% if is_state('switch.boiler_room_pendant', 'on') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      boiler_room_state:
        friendly_name: Boiler Room | State
        value_template: >
        
          {% if is_state('binary_sensor.boiler_room_moisture', 'on') -%}
            problem
          {% elif is_state('switch.boiler_room_pendant', 'on') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}
