automation:
#----------------------------------------------------------------

binary_sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      downstairs_bathroom_occupancy:
        friendly_name: Downstairs Bathroom | Occupancy
        value_template: "{{ is_state('binary_sensor.downstairs_bathroom_motion', 'on') }}"

      downstairs_bathroom_motion:
        friendly_name: Downstairs Bathroom | Motion
        value_template: "{{ is_state('sensor.downstairs_bathroom_burglar', '8') }}"

script:
#----------------------------------------------------------------

  downstairs_bathroom_poweroff_all:
    alias: "Downstairs Bathroom | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.downstairs_bathroom_poweroff_lights
      - service: homeassistant.turn_off
        data:
          entity_id:
            - switch.downstairs_bathroom_fan
            - media_player.downstairs_bathroom_cast

  downstairs_bathroom_poweroff_lights:
    alias: "Downstairs Bathroom | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.downstairs_bathroom_sconce

  downstairs_bathroom_poweron_lights:
    alias: "Downstairs Bathroom | Power On Lights"
    sequence:
      - service: light.turn_on
        entity_id: light.downstairs_bathroom_sconce
        data:
          brightness_pct: 100

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      downstairs_bathroom_on:
        friendly_name: Downstairs Bathroom | On
        value_template: >
          {% set total = 0 %}

          {% if is_state('light.downstairs_bathroom_sconce', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.downstairs_bathroom_fan', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.downstairs_bathroom_cast', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      downstairs_bathroom_state:
        friendly_name: Downstairs Bathroom | State
        value_template: >
          {% if states.sensor.downstairs_bathroom_temperature.state|int < 65 or
                states.sensor.downstairs_bathroom_temperature.state|int > 80 -%}
            problem
          {% elif (is_state('light.downstairs_bathroom_sconce', 'on') or is_state('switch.downstairs_bathroom_fan', 'on')) and states.sensor.downstairs_bathroom_relative_humidity.state|int>70 %}
            showering
          {% elif is_state('binary_sensor.downstairs_bathroom_occupancy', 'on') %}
            active
          {% else %}
            inactive
          {% endif %}
