automation:
#----------------------------------------------------------------

  # Turn off lights when Garage Closed
  - id: 'Garage Door - Ligts Off'
    alias: 'Garage Door - Ligts Off'
    hide_entity: True
    trigger:
      - platform: state
        entity_id: cover.garage
        to: 'closed'
        for:
          hours: 0
          minutes: 10
          seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - switch.garage_dome
          - switch.driveway_sconce
          - light.mudroom_entrance_dome

  # Turn on lights when Garage Opens
  - id: 'Garage Door - Lights On'
    alias: 'Garage Door - Lights On'
    hide_entity: True
    trigger:
      - platform: state
        entity_id: cover.garage
        from: 'closed'
    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_on
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: script.toggle_to_max
        data:
          light: 'light.mudroom_entrance_dome'
      - service: homeassistant.turn_on
        entity_id:
          - switch.garage_dome
          - switch.driveway_sconce

binary_sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      garage_occupancy:
        friendly_name: Garage | Occupancy
        value_template: "{{ is_state('binary_sensor.garage_camera_motion', 'on') or is_state('cover.garage', 'open') or (is_state('cover.garage', 'closed') and is_state('binary_sensor.mudroom_door', 'on')) }}"

  - platform: mqtt
    name: "Garage Camera Motion"
    device_class: motion
    state_topic: "blue_iris/binary_sensor/garage_motion/state"
    payload_on: "ON"
    payload_off: "OFF"  
script:
#----------------------------------------------------------------

  garage_poweroff_all:
    alias: "Garage | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.garage_poweroff_lights
      - service: homeassistant.turn_off
        data:
          entity_id:
            - media_player.garage_cast

  garage_poweroff_lights:
    alias: "Garage | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - switch.garage_dome

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      garage_on:
        friendly_name: Garage | On
        value_template: >
          {% set total = 0 %}

          {% if is_state('switch.garage_dome', 'on') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      garage_state:
        friendly_name: Garage | State
        value_template: >
          {% if is_state('switch.garage_dome', 'on') or
                is_state('cover.garage', 'on') or
                is_state('binary_sensor.garage_occupancy', 'on') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}
