automation:
#----------------------------------------------------------------

binary_sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      garage_occupancy:
        friendly_name: Garage | Occupancy
        value_template: "{{ is_state('binary_sensor.garage_camera_motion', 'on') or is_state('cover.garage', 'open') or (is_state('cover.garage', 'closed') and is_state('binary_sensor.mudroom_door', 'on')) }}"

  - platform: mqtt
    name: "Garage Camera Motion"
    device_class: motion
    state_topic: "blue_iris/binary_sensor/garage_motion/state"
    payload_on: "ON"
    payload_off: "OFF"  

script:
#----------------------------------------------------------------

  garage_poweroff_all:
    alias: "Garage | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.garage_poweroff_lights
      - service: homeassistant.turn_off
        data:
          entity_id:
            - media_player.garage_cast

  garage_poweroff_lights:
    alias: "Garage | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - switch.garage_dome

  telegram_garage_photo:
    alias: 'Garage | Telegram'
    sequence:
      - service: notify.telegram_jesse
        data_template:
          title: "{{ title }}"
          message: "{{ message }}"
          data: 
            video:
              - url: '{{ states.sensor.camera_garage_last_clip.state }}'
                username: !secret camera_username
                password: !secret camera_password
                caption: "{{ caption }}"   

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      garage_on:
        friendly_name: Garage | On
        value_template: >
          {% set total = 0 %}

          {% if is_state('switch.garage_dome', 'on') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      garage_state:
        friendly_name: Garage | State
        value_template: >
          {% if is_state('switch.garage_dome', 'on') or
                is_state('cover.garage', 'on') or
                is_state('binary_sensor.garage_occupancy', 'on') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}
