automation:
#----------------------------------------------------------------

binary_sensor:
#----------------------------------------------------------------

  - platform: mqtt
    name: "Mudroom Camera Motion"
    device_class: motion
    state_topic: "blue_iris/binary_sensor/mudroom_motion/state"
    payload_on: "ON"
    payload_off: "OFF"             

script:
#----------------------------------------------------------------

  mudroom_poweroff_all:
    alias: "Mudroom | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.mudroom_poweroff_lights

  mudroom_poweroff_lights:
    alias: "Mudroom | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.mudroom_entrance_dome
            - light.mudroom_hallway_dome
            - switch.mudroom_closet_dome

  mudroom_poweron_lights:
    alias: "Mudroom | Power On Lights"
    sequence:
      - service: light.turn_on
        entity_id: light.mudroom_entrance_dome
        data:
          brightness_pct: 100
      - service: light.turn_on
        entity_id: light.mudroom_hallway_dome
        data:
          brightness_pct: 100          

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:
      mudroom_on:
        friendly_name: Mudroom | On
        value_template: >
          {% set total = 0 %}

          {% if is_state('light.mudroom_entrance_dome', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.mudroom_hallway_dome', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.mudroom_closet_dome', 'on') %}
            {% set total = total + 1 %}
          {% endif %}          

          {{total}}

      mudroom_state:
        friendly_name: Mudroom | State
        value_template: >
          {% if is_state('binary_sensor.mudroom_motion', 'on') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}
