binary_sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:
      office_moisture:
        friendly_name: Office | Moisture
        value_template: "{{ is_state('sensor.office_leak_sensor_flood', '2') }}"

      office_motion:
        device_class: motion
        value_template: "{{ is_state('binary_sensor.office_ecobee_occupancy', 'on') }}"

      office_occupancy:
        device_class: occupancy
        value_template: "{{ is_state('binary_sensor.office_motion', 'on') }}"

script:
#----------------------------------------------------------------

  office_sleep:
    alias: "Office | Sleep"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.office_dome
      # - service: homeassistant.turn_on
      #   data:
      #     entity_id:
      #       - switch.office_fan

  office_poweroff_all:
    alias: "Office | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.office_poweroff_lights
      # - service: homeassistant.turn_off
      #   data:
      #     entity_id:
      #       - switch.office_fan

  office_poweroff_lights:
    alias: "Office | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.office_dome

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      office_on:
        friendly_name: Office | On
        value_template: >
          {% set total = 0 %}

          {% if is_state('light.office_dome', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.office_ump', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      office_state:
        friendly_name: Office | State
        value_template: >
          {% if is_state('binary_sensor.office_moisture', 'on') or
                states.sensor.office_ecobee_temperature.state|int > 80 or
                states.sensor.office_ecobee_temperature.state|int < 65 -%}
            problem
          {% elif is_state('light.office_dome', 'on') or
                is_state('binary_sensor.office_occupancy', 'on') or
                is_state('media_player.office_ump', 'playing') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}