automation:
#----------------------------------------------------------------

- id: 'Ryans Room - Power Off'
  alias: 'Ryans Room - Power Off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.tracker_ryan
      to: 'Away'
  #Only between 8AM and 9PM, and no motion
  condition:
    - condition: time
      after: '8:00:00'
    - condition: time
      before: '21:00:00'      
    - condition: state
      entity_id: binary_sensor.ryan_s_room_ecobee_occupancy
      state: 'off'        
  action:
    - service: script.turn_on
      data:
        entity_id:
          - script.ryans_room_poweroff_all     

script:
#----------------------------------------------------------------

  ryans_room_sleep:
    alias: "Ryans Room | Sleep"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.ryans_room_dome

  ryans_room_poweroff_all:
    alias: "Ryans Room | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.ryans_room_poweroff_lights
      - service: homeassistant.turn_off
        data:
          entity_id:
            - media_player.ryans_room_ump

  ryans_room_poweroff_lights:
    alias: "Ryans Room | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.ryans_room_dome

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      ryans_room_on:
        friendly_name: Ryans Room | On
        value_template: >
          {% set total = 0 %}

          {% if is_state('media_player.ryan_s_room_ump', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      ryans_room_state:
        friendly_name: Ryans Room | State
        value_template: >
          {% if states.sensor.ryan_s_room_ecobee_temperature.state|int > 80 or
                states.sensor.ryan_s_room_ecobee_temperature.state|int < 65 -%}
            problem
          {% elif is_state('binary_sensor.ryan_s_room_ecobee_occupancy', 'on') or
                is_state('media_player.ryan_s_room_ump', 'playing') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}
