binary_sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      storage_room_moisture:
        friendly_name: Storage Room | Moisture
        value_template: "{{ is_state('sensor.storage_room_leak_sensor_flood', '2') }}"

      storage_room_motion:
        friendly_name: Storage Room | Motion
        value_template: "{{ is_state('binary_sensor.storage_room_camera_motion', 'on')  }}"

      storage_room_occupancy:
        friendly_name: Storage Room | Occupancy
        value_template: "{{ is_state('binary_sensor.storage_room_motion', 'on') or is_state('binary_sensor.storage_room_door', 'on') or is_state('binary_sensor.storage_room_freezer_door', 'on') }}"

input_boolean:
#----------------------------------------------------------------

  storage_room_ceiling_light:

light:
#----------------------------------------------------------------

  - platform: template
    lights:
      storage_room_ceiling:
        value_template: "{{ states('input_boolean.storage_room_ceiling_light') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.storage_room_ceiling_light
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.storage_room_ceiling_light

script:
#----------------------------------------------------------------

  storage_room_poweroff_all:
    alias: "Storage Room | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.storage_room_poweroff_lights

  storage_room_poweroff_lights:
    alias: "Storage Room | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.storage_room_ceiling

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      storage_room_on:
        friendly_name: Storage Room | On
        value_template: >
          {% set total = 0 %}

          {% if is_state('light.storage_room_ceiling', 'on') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      storage_room_state:
        friendly_name: Storage Room | State
        value_template: >
          {% if is_state('binary_sensor.storage_room_moisture', 'on') -%}
            problem
          {% elif is_state('light.storage_room_ceiling', 'on') or
                is_state('binary_sensor.storage_room_freezer_door', 'on') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}
