homeassistant:
#----------------------------------------------------------------
  customize:

    switch.theater_posters:
      icon: mdi:account-box-outline

    switch.theater_candy:
      icon: mdi:candycane

    media_player.theater_ump:
      icon: mdi:shield

    light.theater_aisle:
      icon: mdi:led-strip
      friendly_name: Theater | Lightstrip

    light.theater_candy:
      icon: mdi:candycane
      friendly_name: Theater | Candy      

automation:
#----------------------------------------------------------------           

binary_sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      # if battery motion sensor is offline, use camera motion
      theater_motion:
        friendly_name: "Theater | Motion"
        device_class: motion
        value_template: >-
          {% if is_state('sensor.theater_motion_burglar', '8') %}
            true
          {% elif is_state('sensor.theater_motion_burglar', '0') %}
            false
          {% else %}
            {{ states('binary_sensor.theater_camera_motion') }}
          {% endif %}        

      theater_aisle_motion:
        friendly_name: Theater | Aisle Motion
        device_class: motion
        value_template: "{{ is_state('sensor.theater_aisle_motion_burglar', '8') }}"

      theater_occupancy:
        friendly_name: Theater | Occupancy
        value_template: "{{ is_state('binary_sensor.theater_motion', 'on') or
                            is_state('binary_sensor.theater_aisle_motion', 'on') }}"

  - platform: mqtt
    name: "Theater Camera Motion"
    device_class: motion
    state_topic: "blue_iris/binary_sensor/theater_motion/state"
    payload_on: "ON"
    payload_off: "OFF"

input_boolean:
#----------------------------------------------------------------

  theater_state:
    initial: off

light:
#----------------------------------------------------------------

script:
#----------------------------------------------------------------

  theater_poweroff_all:
    alias: "Theater | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.theater_poweroff_lights
      - service: homeassistant.turn_off
        data:
          entity_id:
            - media_player.theater_ump
            - media_player.theater_cast

  theater_poweroff_lights:
    alias: "Theater | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.theater_wall_sconce
            - switch.theater_posters
            - light.theater_candy
            - light.theater_aisle

  theater_poweron_lights:
    alias: "Theater | Power On Lights"
    sequence:            
      - service: light.turn_on
        entity_id: light.theater_wall_sconce
        data:
          brightness_pct: 100         
      - service: switch.turn_on
        entity_id:
          - switch.theater_posters
      - service: light.turn_on
        data:
          entity_id:
            - light.theater_candy
            - light.theater_aisle
          brightness_pct: 100
          effect: LSD          

  theater_poweron_aisle_lights:
    alias: 'Theater - Aisle On'
    sequence:            
      - service: light.turn_on
        data:
          entity_id:
            - light.theater_candy
          brightness_pct: 1
          color_name: yellow  
      - service: light.turn_on
        data:
          entity_id:
            - light.theater_candy
            - light.theater_aisle
          brightness_pct: 1
          color_name: red            

  theater_poweroff_aisle_lights:
    alias: 'Theater - Aisle Off'
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.theater_candy
            - light.theater_aisle                  

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      theater_on:
        friendly_name: Theater | On
        value_template: >
          {% set total = 0 %}

          {% if is_state('light.theater_aisle', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.theater_wall_sconce', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.theater_posters', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.theater_candy', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.theater_cast', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      theater_state:
        friendly_name: Theater | State
        value_template: >
          {% if states.sensor.theater_ecobee_temperature.state|int > 80 or
                states.sensor.theater_ecobee_temperature.state|int < 61 -%}
            problem
          {% elif states.remote.theater.attributes.current_activity != "PowerOff" or
                is_state('binary_sensor.theater_occupancy', 'on') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}
     
      theater_hub_activity:
        friendly_name: Theater | Hub (Activity)
        value_template: >
          {{ states.remote.theater.attributes.current_activity }}