homeassistant:
#----------------------------------------------------------------
  customize:

    switch.theater_posters:
      icon: mdi:account-box-outline

    switch.theater_candy:
      icon: mdi:candycane

    media_player.theater_ump:
      icon: mdi:shield

    light.yeelight_strip2_04cf8c7d60e9:
      icon: mdi:led-strip
      friendly_name: Theater | Lightstrip

automation:
#----------------------------------------------------------------

  # turn on main lights if motion and nothing playing
  - id: 'Theater - Main Lights On'
    alias: 'Theater - Main Lights On'
    trigger:
      - platform: state
        entity_id: binary_sensor.theater_motion
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" }}'
      - condition: state
        entity_id: input_boolean.options_lights_auto_on
        state: 'on'
    action:
      - service: script.turn_on
        data:
          entity_id:
            - script.theater_poweron_lights

  # turn off lights if no motion for 5 minutes and nothing is playing
  - id: 'Theater - Lights Off'
    alias: 'Theater - Lights Off'
    trigger:
      - platform: state
        entity_id: binary_sensor.theater_motion
        to: 'off'
        for:
          hours: 0
          minutes: 5
          seconds: 0
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" }}'
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'
    action:
      - service: script.turn_on
        data:
          entity_id:
            - script.theater_poweroff_lights

  # Turn off theater lights when something starts playing
  - id: 'Theater - Start Playing'
    alias: 'Theater - Start Playing'
    trigger:
      platform: state
      entity_id: remote.theater
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.attributes.current_activity != "PowerOff" }}'
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'
    action:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.theater_wall_sconce
            - switch.theater_posters
            - switch.theater_candy
      - service: light.turn_on
        data:
          entity_id: light.yeelight_strip2_04cf8c7d60e9
          brightness_pct: 1
          color_name: red    

  # Turn on theater lights when playing stops
  - id: 'Theater - Stop Playing'
    alias: 'Theater - Stop Playing'
    trigger:
      platform: state
      entity_id: remote.theater
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" }}'
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'
    action:
      - service: script.turn_on
        data:
          entity_id:
            - script.theater_poweron_lights    

  # turn on aisle lights if aisle motion and something is playing
  - id: 'Theater - Aisle Lights On'
    alias: 'Theater - Aisle Lights On'
    trigger:
      - platform: state
        entity_id: binary_sensor.theater_aisle_motion
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.attributes.current_activity != "PowerOff" }}'
      - condition: state
        entity_id: input_boolean.options_lights_auto_on
        state: 'on'
    action:
      - service: script.turn_on
        data:
          entity_id:
            - script.theater_poweron_aisle_lights   

    # turn off aisle lights if no motion for 2 minutes and something is playing
  - id: 'Theater - Aisle Lights Off'
    alias: 'Theater - Aisle Lights Off'
    trigger:
      - platform: state
        entity_id: binary_sensor.theater_aisle_motion
        to: 'off'
        for:
          hours: 0
          minutes: 2
          seconds: 0
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.attributes.current_activity != "PowerOff" }}'
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'
    action:
      - service: script.turn_on
        data:
          entity_id:
            - script.theater_poweroff_aisle_lights              

binary_sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:
      theater_motion:
        friendly_name: Theater | Motion
        value_template: "{{ is_state('sensor.theater_motion_burglar', '8') }}"

      theater_aisle_motion:
        friendly_name: Theater | Aisle Motion
        value_template: "{{ is_state('sensor.theater_aisle_motion_burglar', '8') }}"

      theater_occupancy:
        friendly_name: Theater | Occupancy
        value_template: "{{ is_state('binary_sensor.theater_motion', 'on') or
                            is_state('binary_sensor.theater_aisle_motion', 'on') }}"

  - platform: mqtt
    name: "Theater Camera Motion"
    device_class: motion
    state_topic: "blue_iris/binary_sensor/theater_motion/state"
    payload_on: "ON"
    payload_off: "OFF"

input_boolean:
#----------------------------------------------------------------

  theater_state:
    initial: off

light:
#----------------------------------------------------------------

script:
#----------------------------------------------------------------

  theater_poweroff_all:
    alias: "Theater | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.theater_poweroff_lights
      - service: homeassistant.turn_off
        data:
          entity_id:
            - media_player.theater_ump
            - media_player.theater_cast

  theater_poweroff_lights:
    alias: "Theater | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.theater_wall_sconce
            - switch.theater_posters
            - switch.theater_candy
            - light.yeelight_strip2_04cf8c7d60e9

  theater_poweron_lights:
    alias: "Theater | Power On Lights"
    sequence:            
      - service: script.toggle_to_max
        data:
          light: 'light.theater_wall_sconce'              
      - service: homeassistant.turn_on
        entity_id:
          - switch.theater_posters
          - switch.theater_candy
      - service: light.turn_on
        data:
          entity_id: light.yeelight_strip2_04cf8c7d60e9
          brightness_pct: 100
          color_name: blue

  theater_poweron_aisle_lights:
    alias: 'Theater - Aisle On'
    sequence:            
      - service: homeassistant.turn_on
        entity_id:
          - switch.theater_candy
      - service: light.turn_on
        data:
          entity_id: light.yeelight_strip2_04cf8c7d60e9
          brightness_pct: 1
          color_name: red  

  theater_poweroff_aisle_lights:
    alias: 'Theater - Aisle Off'
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - switch.theater_candy
            - light.yeelight_strip2_04cf8c7d60e9                  

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      theater_on:
        friendly_name: Theater | On
        value_template: >
          {% set total = 0 %}

          {% if is_state('light.yeelight_strip2_04cf8c7d60e9', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.theater_wall_sconce', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.theater_posters', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.theater_candy', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.theater_cast', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      theater_state:
        friendly_name: Theater | State
        value_template: >
          {% if states.sensor.theater_ecobee_temperature.state|int > 80 or
                states.sensor.theater_ecobee_temperature.state|int < 61 -%}
            problem
          {% elif states.remote.theater.attributes.current_activity != "PowerOff" or
                is_state('binary_sensor.theater_occupancy', 'on') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}
