- type: custom:compact-custom-header

- type: vertical-stack
  cards:
    - type: markdown
      content: >
        ## [![Home](/local/images/menu/double-left_16.png)](/lovelace/home?kiosk&show_tabs)&emsp;CARS

    - type: glance
      show_name: false
      entities:
        - entity: binary_sensor.cars_problems
          name: ' '
        - entity: sensor.cars_open
          name: ' '

    - type: custom:monster-card
      show_empty: false
      card:
        type: entities
        show_header_toggle: false
        title: WARNING
        theme: "warning"
      filter:
        include:
          - entity_id: "lock.*"
            state: "unlocked"
          - entity_id: "sensor.volvo_xc90_fuel_level"
            state: "< 10"
          - entity_id: "sensor.i3_charging_level_hv"
            state: "< 10"

# CARINA
#----------------------------------------------------------------
    - type: markdown
      content: >
        ## [![Home](/local/images/menu/double-left_16.png)](/lovelace/home?kiosk&show_tabs)&emsp;CARINA | VOLVO XC90

    - type: picture-glance
      entities: []
      state_image:
        "active": /local/images/stock/xc90_active.jpg
        "inactive": /local/images/stock/xc90_inactive.jpg
        "problem": /local/images/stock/xc90_problem.jpg
      entity: sensor.cars_xc90_state

    - type: horizontal-stack
      cards:
        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_service
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: Service
          action: more_info
          color_type: card
          size: 30px 
          icon: mdi:wrench
          style:
            - color: white                      

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_bulbs
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: Bulbs
          action: more_info
          color_type: card
          size: 30px      
          icon: mdi:lightbulb
          style:
            - color: white

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_hood
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: Hood
          action: more_info
          color_type: card
          size: 30px      
          icon: mdi:angle-acute
          style:
            - color: white         
                                            
        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_washer_fluid
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: Washer
          action: more_info
          color_type: card
          size: 30px      
          icon: mdi:water
          style:
            - color: white

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_brake_fluid
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: Brakes
          action: more_info
          color_type: card
          size: 30px
          icon: mdi:stop-circle
          style:
            - color: white                                      

    - type: horizontal-stack
      cards:
        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_windows
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: Windows
          action: more_info
          color_type: card
          size: 30px 
          icon: mdi:window-closed
          style:
            - color: white                              

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_front_left_window
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: F Left
          action: more_info
          color_type: card
          size: 30px 
          icon: mdi:window-closed
          style:
            - color: white                      

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_front_right_window
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: F Right
          action: more_info
          color_type: card
          size: 30px 
          icon: mdi:window-closed
          style:
            - color: white                              

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_rear_left_window
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: R Left
          action: more_info
          color_type: card
          size: 30px  
          icon: mdi:window-closed
          style:
            - color: white                             

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_rear_right_window
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: R Right
          action: more_info
          color_type: card
          size: 30px
          icon: mdi:window-closed
          style:
            - color: white                             

    - type: horizontal-stack
      cards:
        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_doors
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: Doors
          action: more_info
          color_type: card
          size: 30px  
          icon: mdi:car-door
          style:
            - color: white  

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_front_left_door
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: F Left
          action: more_info
          color_type: card
          size: 30px 
          icon: mdi:car-door
          style:
            - color: white                      

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_front_right_door
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: F Right
          action: more_info
          color_type: card
          size: 30px 
          icon: mdi:car-door
          style:
            - color: white                              

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_rear_left_door
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: R Left
          action: more_info
          color_type: card
          size: 30px  
          icon: mdi:car-door
          style:
            - color: white                             

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_rear_right_door
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: R Right
          action: more_info
          color_type: card
          size: 30px
          icon: mdi:car-door
          style:
            - color: white   

    - type: horizontal-stack
      cards:
        - type: "custom:button-card"
          color_type: blank-card
          size: 30px             

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_front_left_tyre
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: F Left
          action: more_info
          color_type: card
          size: 30px 
          icon: mdi:album
          style:
            - color: white                      

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_front_right_tyre
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: F Right
          action: more_info
          color_type: card
          size: 30px 
          icon: mdi:album
          style:
            - color: white                              

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_rear_left_tyre
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: R Left
          action: more_info
          color_type: card
          size: 30px  
          icon: mdi:album
          style:
            - color: white                             

        - type: "custom:button-card"
          entity: binary_sensor.volvo_xc90_rear_right_tyre
          color_off: rgb(31, 31, 40)
          color: darkred   
          show_state: no
          name: R Right
          action: more_info
          color_type: card
          size: 30px
          icon: mdi:album
          style:
            - color: white                                                         

    - type: custom:monster-card
      show_empty: false
      card:
        type: entities
        show_header_toggle: false
      filter:
        include:
          - entity_id: device_tracker.volvo_yv4a22pk2h1184894
            options:
              name: Location
          - entity_id: sensor.volvo_xc90_fuel_level
            options:
              name: Fuel
          - entity_id: "lock.volvo_xc90_door_lock"
            options:
              name: Doors | Locked
            state: "locked"
          - entity_id: "lock.volvo_xc90_door_lock"
            options:
              name: Doors | Unlocked
            state: "unlocked"

# JESSE
#----------------------------------------------------------------
    - type: markdown
      content: >
        ## [![Home](/local/images/menu/double-left_16.png)](/lovelace/home?kiosk&show_tabs)&emsp;JESSE | BMW i3

    - type: picture-glance
      entities: []
      state_image:
        "active": /local/images/stock/i3_active.jpg
        "inactive": /local/images/stock/i3_inactive.jpg
        "problem": /local/images/stock/i3_problem.jpg
      entity: sensor.cars_i3_state

    - type: custom:monster-card
      show_empty: false
      card:
        type: entities
        show_header_toggle: false
      filter:
        include:
          - entity_id: device_tracker.i3_94_rex
            options:
              name: Location
          - entity_id: sensor.juicenet_charging_status
            options:
              name: Charge Status
          - entity_id: sensor.i3_94_rex_charging_level_hv
            options:
              name: Charge Level
          - entity_id: "lock.i3_94_rex_lock"
            options:
              name: Doors | Locked
            state: "locked"
          - entity_id: "lock.i3_94_rex_lock"
            options:
              name: Doors | Unlocked
            state: "unlocked"
