- type: custom:compact-custom-header

- type: vertical-stack
  cards:
    - type: markdown
      content: >
        ## [![Home](/local/images/menu/double-left_16.png)](/lovelace/home?kiosk&show_tabs)&emsp;OPTIONS

# LIGHTS
#----------------------------------------------------------------
    - type: markdown
      content: >
        ## [![Home](/local/images/menu/double-left_16.png)](/lovelace/home?kiosk&show_tabs)&emsp;LIGHTS

    - type: entities
      entities:
        - entity: input_boolean.options_lights_auto_off
        - entity: input_boolean.options_lights_auto_on

# NOTIFICATIONS
#----------------------------------------------------------------
    - type: markdown
      content: >
        ## [![Home](/local/images/menu/double-left_16.png)](/lovelace/home?kiosk&show_tabs)&emsp;NOTIFICATIONS

    - type: entities
      entities:
        - entity: input_boolean.options_notifications_chime
        - entity: input_boolean.options_notifications_push
        - entity: input_boolean.options_notifications_speech

    - type: custom:tracker-card