- type: custom:compact-custom-header

- type: vertical-stack
  cards:

# SYSTEM
#----------------------------------------------------------------

    - type: entities
      title: System
      show_header_toggle: false
      entities:
        - entity: sensor.installed_version
          name: Installed Version
          icon: mdi:home-assistant
        - entity: sensor.latest_available_version
          name: Latest Version
          icon: mdi:home-assistant

        - type: divider

        - entity: sensor.last_boot_date_time
          icon: mdi:calendar
        - entity: sensor.nuc_uptime
          icon: mdi:clock-start
        - entity: sensor.ha_uptime
          icon: mdi:home-assistant

        - type: custom:bar-card
          title: Processor Use
          entity: sensor.processor_use
          height: 30px
          animation: 'off'
          indicator: 'off'
          severity:
            - value: 60
              color: green
            - value: 85 
              color: orange
            - value: 100
              color: red

        - type: custom:bar-card
          title: CPU Temp
          entity: sensor.cpu_temperature
          animation: 'off'
          indicator: 'off'
          height: 30px
          severity:
            - value: 60
              color: green
            - value: 70 
              color: orange
            - value: 100
              color: red

        - type: custom:bar-card
          title: Memory Use
          entity: sensor.memory_use_percent
          height: 30px
          animation: 'off'
          indicator: 'off'
          severity:
            - value: 60
              color: green
            - value: 85 
              color: orange
            - value: 100
              color: red

        - type: custom:bar-card
          title: Disk Use
          entity: sensor.disk_use_percent
          height: 30px
          animation: 'off'
          indicator: 'off'
          severity:
            - value: 60
              color: green
            - value: 85 
              color: orange
            - value: 100
              color: red


# COMPONENTS
#----------------------------------------------------------------

    - type: custom:tracker-card
      title:
      trackers:
        - sensor.custom_card_tracker
        - sensor.custom_component_tracker