binary_sensor:
#----------------------------------------------------------------

  - platform: mqtt
    name: "Dining Room Camera Motion"
    device_class: motion
    state_topic: "blue_iris/binary_sensor/dining_room_motion/state"
    payload_on: "ON"
    payload_off: "OFF"  
    
  - platform: template
    sensors:

      dining_room_occupancy:
        value_template: "{{ is_state('binary_sensor.dining_room_motion', 'on') }}"

      dining_room_motion:
        value_template: "{{ is_state('binary_sensor.dining_room_camera_motion', 'on') }}"

script:
#----------------------------------------------------------------

  dining_room_poweroff_all:
    alias: "Dining Room | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.dining_room_poweroff_lights
      - service: homeassistant.turn_off
        data:
          entity_id:
            - media_player.dining_room_cast

  dining_room_poweroff_lights:
    alias: "Dining Room | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.dining_room_pendant

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:
      
      dining_room_on:
        value_template: >
          {% set total = 0 %}

          {% if is_state('light.dining_room_pendant', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.dining_room_cast', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      dining_room_state:
        value_template: >
          {% if is_state('light.dining_room_pendant', 'on') or
                is_state('binary_sensor.dining_room_occupancy', 'on') or
                is_state('media_player.dining_room_cast', 'playing') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}
