binary_sensor:
#----------------------------------------------------------------
  - platform: mqtt
    name: "Kitchen Camera Motion"
    device_class: motion
    state_topic: "blue_iris/binary_sensor/kitchen_motion/state"
    payload_on: "ON"
    payload_off: "OFF" 

  - platform: template
    sensors:

      kitchen_occupancy:
        value_template: "{{ is_state('binary_sensor.kitchen_motion', 'on') or
                            is_state('binary_sensor.kitchen_door', 'on') }}"

      kitchen_motion:
        value_template: "{{ is_state('binary_sensor.kitchen_camera_motion', 'on') or
                            is_state('binary_sensor.kitchen_microwave', 'on') }}"

      kitchen_microwave:
        value_template: "{{ not (is_state('sensor.sense_c0ab8d51', '0') or
                            is_state('sensor.sense_c0ab8d51', 'unknown')) }}"

script:
#----------------------------------------------------------------

  kitchen_poweroff_all:
    alias: "Kitchen | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.kitchen_poweroff_lights
      - service: homeassistant.turn_off
        data:
          entity_id:
            - media_player.kitchen_table_cast
            - media_player.kitchen_sink_cast
            - media_player.kitchen_ump

  kitchen_poweroff_lights:
    alias: "Kitchen | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - switch.kitchen_recessed2
            - switch.kitchen_pendant

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:
      kitchen_on:
        value_template: >
          {% set total = 0 %}

          {% if is_state('switch.kitchen_recessed2', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.kitchen_pendant', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.kitchen_ump', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.kitchen_cast', 'playing') %}
            {% set total = total + 1 %}
          {% else %}
            {% if is_state('media_player.kitchen_table_cast', 'playing') %}
              {% set total = total + 1 %}
            {% endif %}          
            {% if is_state('media_player.kitchen_sink_cast', 'playing') %}
              {% set total = total + 1 %}
            {% endif %}                    
          {% endif %}

          {{total}}

      kitchen_state:
        value_template: >
          {% if states.sensor.kitchen_sensor_ecobee_temperature.state|int > 80 or
                states.sensor.kitchen_sensor_ecobee_temperature.state|int < 65 -%}
            problem
          {% elif is_state('switch.kitchen_recessed2', 'on') or
                is_state('switch.kitchen_pendant', 'on') or
                is_state('binary_sensor.kitchen_occupancy', 'on') or
                is_state('binary_sensor.kitchen_microwave', 'on') or
                is_state('media_player.kitchen_ump', 'playing') or
                is_state('media_player.kitchen_cast', 'playing') or
                is_state('media_player.kitchen_table_cast', 'playing') or
                is_state('media_player.kitchen_sink_cast', 'playing') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}
