script:
#----------------------------------------------------------------
  master_bedroom_sleep:
    alias: "Master Bedroom | Sleep"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.master_bedroom_front_pendant
            - light.master_bedroom_wall_sconce
            - light.master_bedroom_rear_pendant
            - fan.master_bedroom_front
            - fan.master_bedroom_rear
            - light.master_bedroom_jesse_lamp
            - light.master_bedroom_carina_lamp            
      - service: homeassistant.turn_on
        data:
          entity_id: fan.master_bedroom_rear
      - service: fan.set_speed
        entity_id: fan.master_bedroom_rear
        data:
          speed: high

  master_bedroom_poweroff_all:
    alias: "Master Bedroom | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.master_bedroom_poweroff_lights
      - service: homeassistant.turn_off
        data:
          entity_id:
            - fan.master_bedroom_front
            - fan.master_bedroom_rear
            - switch.master_bedroom_ac
            - media_player.master_bedroom_ump
            - media_player.master_bedroom_cast
            - light.master_bedroom_jesse_lamp
            - light.master_bedroom_carina_lamp            

  master_bedroom_poweroff_lights:
    alias: "Master Bedroom | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.master_bedroom_front_pendant
            - light.master_bedroom_rear_pendant
            - light.master_bedroom_wall_sconce
            - light.master_bedroom_jesse_lamp
            - light.master_bedroom_carina_lamp            

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      master_bedroom_on:
        value_template: >
          {% set total = 0 %}

          {% if is_state('light.master_bedroom_jesse_lamp', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.master_bedroom_carina_lamp', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.master_bedroom_front_pendant', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.master_bedroom_rear_pendant', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.master_bedroom_wall_sconce', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('fan.master_bedroom_front', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('fan.master_bedroom_rear', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.master_bedroom_ac', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.master_bedroom_ump', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.master_bedroom_cast', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      master_bedroom_state:
        value_template: >
          {% if states.sensor.master_bedroom_ecobee_temperature.state|int> 80 or
                states.sensor.master_bedroom_ecobee_temperature.state|int<65 -%}
            problem
          {% elif is_state('light.master_bedroom_front_pendant', 'off') and
                is_state('light.master_bedroom_rear_pendant', 'off') and
                is_state('light.master_bedroom_wall_sconce', 'off') and
                is_state('fan.master_bedroom_rear', 'on') -%}
            sleeping
          {% elif is_state('light.master_bedroom_front_pendant', 'on') or
                is_state('light.master_bedroom_jesse_lamp', 'on') or
                is_state('light.master_bedroom_carina_lamp', 'on') or
                is_state('light.master_bedroom_rear_pendant', 'on') or
                is_state('light.master_bedroom_wall_sconce', 'on') or                
                is_state('fan.master_bedroom_front', 'on') or
                is_state('fan.master_bedroom_rear', 'on') or
                is_state('switch.master_bedroom_ac', 'on') or
                is_state('media_player.master_bedroom_ump', 'playing') or
                is_state('media_player.master_bedroom_cast', 'playing') or
                is_state('binary_sensor.master_bedroom_ecobee_occupancy', 'on') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}

switch:
#----------------------------------------------------------------

  - platform: template
    switches:
      sleep_dash:
        value_template: "{{ is_state('sensor.master_bedroom_activity', 'Sleeping') }}"
        turn_on:
          - service: script.turn_on
            data:
              entity_id:
                - script.master_bedroom_sleep
        turn_off:
          - service: script.turn_on
            data:
              entity_id:
                - script.master_bedroom_poweroff_all
