binary_sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:

      master_bathroom_occupancy:
        value_template: "{{ is_state('binary_sensor.master_bathroom_ceiling_light', 'on') }}"

      master_bathroom_ceiling_light:
        value_template: "{{ is_state('binary_sensor.light_master_bathroom', 'on') }}"

script:
#----------------------------------------------------------------

  master_bathroom_poweroff_all:
    alias: "Master Bathroom | Power Off All"
    sequence:
      # - service: script.turn_on
      #   data:
      #     entity_id:
      #       - script.master_bathroom_poweroff_lights
      - service: homeassistant.turn_off
        data:
          entity_id:
            - media_player.master_bathroom_cast

  # master_bathroom_poweroff_lights:
  #   alias: "Master Bathroom | Power Off Lights"
  #   sequence:
  #     - service: homeassistant.turn_off
  #       data:
  #         entity_id:
  #           - light.master_bathroom_ceiling

sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:
      master_bathroom_on:
        value_template: >
          {% set total = 0 %}

          {% if is_state('light.master_bathroom_ceiling', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.master_bathroom_cast', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      master_bathroom_state:
        value_template: >
          {% if is_state('light.master_bathroom_ceiling', 'on') or
                is_state('media_player.upstairs_bathroom_cast', 'playing') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}
