automation:
#----------------------------------------------------------------

  - id: 'Sunroom - Lights Off'
    alias: 'Sunroom - Power Off'
    trigger:
      - platform: state
        entity_id: binary_sensor.sunroom_room_motion
        to: 'off'
        for:
          hours: 0
          minutes: 10
          seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.options_lights_auto_off
        state: 'on'
    action:
      - service: script.turn_on
        data:
          entity_id:
            - script.sunroom_poweroff_all

  # Turn on light when motion detected
  - id: 'Sunroom | Lights On'
    alias: 'Sunroom | Lights On'
    trigger:
      platform: state
      entity_id: binary_sensor.sunroom_room_motion
      to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.sunroom_poweron_lights

binary_sensor:
#----------------------------------------------------------------
  - platform: mqtt
    name: "Sunroom Camera Motion"
    device_class: motion
    state_topic: "blue_iris/binary_sensor/sunroom_motion/state"
    payload_on: "ON"
    payload_off: "OFF" 

  - platform: template
    sensors:

      sunroom_occupancy:
        device_class: occupancy
        value_template: "{{ is_state('binary_sensor.sunroom_motion', 'on') }}"

      sunroom_room_motion:
        device_class: motion
        value_template: "{{ is_state('sensor.sunroom_motion_burglar', '8') }}"

input_boolean:
#----------------------------------------------------------------
  sunroom_state:
    initial: off

script:
#----------------------------------------------------------------

  sunroom_poweroff_all:
    alias: "Sunroom | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.sunroom_poweroff_lights
      - service: homeassistant.turn_off
        data:
          entity_id:
            - media_player.sunroom_cast

  sunroom_poweroff_lights:
    alias: "Sunroom | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.sunroom_left_sconce
            - switch.sunroom_center_sconce
            - switch.sunroom_right_sconce

  sunroom_poweron_lights:
    alias: "Sunroom | Power Off Lights"
    sequence:
      - service: script.toggle_to_max
        data:
          light: 'light.sunroom_left_sconce'    
      - service: homeassistant.turn_on
        entity_id:
          - switch.sunroom_center_sconce
          - switch.sunroom_right_sconce
sensor:
#----------------------------------------------------------------

  - platform: template
    sensors:
      sunroom_on:
        value_template: >
          {% set total = 0 %}

          {% if is_state('light.sunroom_left_sconce', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.sunroom_center_sconce', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.sunroom_right_sconce', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('media_player.sunroom_cast', 'playing') %}
            {% set total = total + 1 %}
          {% endif %}

          {{total}}

      sunroom_state:
        value_template: >
          {% if is_state('light.sunroom_left_sconce', 'on') or
                is_state('switch.sunroom_center_sconce', 'on') or
                is_state('switch.sunroom_right_sconce', 'on') or
                is_state('media_player.sunroom_cast', 'playing') or
                is_state('binary_sensor.sunroom_occupancy', 'on') -%}
            active
          {%- else -%}
            inactive
          {%- endif %}
