automation:
#----------------------------------------------------------------

script:
#----------------------------------------------------------------

  exterior_poweroff_all:
    alias: "Exterior | Power Off All"
    sequence:
      - service: script.turn_on
        data:
          entity_id:
            - script.exterior_poweroff_lights
            
            # - script.pool_poweroff_all
      # - service: homeassistant.turn_off
      #   data:
      #     entity_id:
      #       - switch.exterior_front_water
      #       - switch.exterior_front_accessory

  exterior_poweroff_lights:
    alias: "Exterior | Power Off Lights"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.front_door_sconce
            - switch.driveway_sconce
            - switch.porch_sconce